package cmd

import "github.com/spf13/cobra"

var tfCmd = &cobra.Command{
	Use:   "tf",
	Short: "Run Terraform over Cloudfauj infrastructure",
	Long: `
    This command lets you run Terraform over all configuration generated by
    Cloudfauj for your infrastructure.
    It invokes the same Terraform binary used by Cloudfauj to manage resources,
    guaranteeing consistency.`,
}
